# pull official base image
FROM python:3.9-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
# COPY ./boot.sh /usr/src/app/boot.sh
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/

# ENTRYPOINT ["/usr/src/app/docker/app/entrypoint.sh"]

# RUN chmod u+x boot.sh

# ENTRYPOINT ["/bin/sh","boot.sh"]
