services:
  web:
    build: 
      context: ./docker/app
      dockerfile: Dockerfile-dev
    command: flask run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db
  # db:
  #   image: postgres:13
  #   volumes:
  #     - /docker/postgres/db-data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_flask
  #     - POSTGRES_PASSWORD=hello_flask
  #     - POSTGRES_DB=hello_flask_dev

  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: techster-postgres
    #container_name: cajui-db
    ports:
      - "5432:5432"
    #restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./docker/postgres/db-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
