version: '3.8'

services:
  web1:
    build: .
    volumes:
      - ./:/var/www/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    build: 
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: techster-db
    ports:
      - "5432:5432"
    #restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./docker/postgres/db-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d